name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release

    - name: Package Artifacts
      run: |
        mkdir -p release_artifacts
        # Example: cp build/myapp release_artifacts/
        tar -czvf release.tar.gz -C ${{github.workspace}}/build .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cpp-release-build
        path: release.tar.gz
