name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get

    - name: Lint
      run: flutter analyze

    - name: Test
      run: flutter test

    - name: Build APK (Release)
      run: flutter build apk --release

    # Uncomment if web build is needed
    # - name: Build Web
    #   run: flutter build web --release

    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v4
      with:
        name: flutter-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
