name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Test
      run: ./gradlew test --no-daemon

    - name: Upload Artifact (JAR)
      uses: actions/upload-artifact@v4
      with:
        name: java-release-build
        path: build/libs/*.jar
