name: Web CI (Node.js)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint --if-present

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test

    - name: Upload Artifact (Build Output)
      uses: actions/upload-artifact@v4
      with:
        name: web-release-build
        path: dist/ # Adjust if using build/ or out/
